const jokes = [
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What do you call an onion that's a detective? An Investi-Gator!",
    "Why did the lettuce leaf leave the garden? Because it was feeling wilted.",
    "What did the carrot say to the celery? 'I think you're a bit of a stalk!'",
    "Why did the sweet potato become a cheerleader? Because it was always yam-ing!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the cookie go to the doctor? Because it was feeling crumbly.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Why was the math book sad? Because it had too many problems.",
    "Why was the computer cold? Because it left its Windows open!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the football team go to the bank? To get their quarterback!",
    "Why did the hipster burn his tongue? He drank his coffee before it was cool.",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one!",
    "Why did the cookie go to the party? Because it was a great crumb!",
    "Why did the shark cross the ocean? To get to the other tide!",
    "Why did the man put his money in the freezer? He wanted cold hard cash!",
    "Why did the cookie go to the therapist? It was feeling crumbly.",
    "Why did the skeleton go to the bar? To get a little body!",
    "Why did the bicycle fall off the cliff? It was two-tired!",
    "Why did the cookie go to space? To see the Milky Way!",
    "Why did the tomato turn red? It saw the salad dressing!",
    "Why did the man put his money in the blender? He wanted liquid assets!",
    "Why did the elephant wear a tutu? Because it wanted to be a ballerina!",
    "Why did the cookie go to the doctor? Because it needed a check-up!",
    "Why did the cat join the Red Cross? It wanted to be a first-aid kit!",
    "Why did the duck go to the doctor? Because it was feeling a little down!",
    "Why did the man put his money in a blender? He wanted liquid assets!",
    "Why did the cookie go to the vet? Because it felt crumbly!",
    "Why did the dog cross the road? To get to the bark-ing lot!",
    "Why did the man put his money in the oven? He wanted to have warm cash!",
    "Why did the cookie go to school? To learn how to be a crumb-inator!",
    "Why did the tomato turn red? It saw the salad dressing!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the cookie go to the meeting? To discuss crumb issues!",
    "Why did the man put his money in the microwave? He wanted hot cash!",
    "Why did the coffee file a police report? It got mugged!",
    "Why did the math book look so mad? It had too many problems!",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why did the computer go to the doctor? It had a virus!",
    "Why did the bicycle fall over? Because it was two-tired!",
    "Why did the cookie go to the hospital? Because it felt crumbly!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the duck go to the doctor? He had the flu!",
    "Why did the frog call his insurance company? He had a jump in his car!",
    "Why did the horse go to the doctor? It had a cough!",
    "Why did the calendar become popular? It had a lot of dates!",
    "Why did the fish go to school? To learn how to swim!",
    "Why did the giraffe go to the doctor? It had a sore throat!",
    "Why did the ghost go to the bar? For a booze cruise!",
    "Why did the hipster burn his tongue? He drank his coffee before it was cool!",
    "Why did the kangaroo go to the doctor? It had a hopping cough!",
    "Why did the man put his money in the freezer? He wanted cold hard cash!",
    "Why did the monkey go to the zoo? To see its cousin!",
    "Why did the moon go to the doctor? It had a bad case of eclipse!",
    "Why did the mushroom go to the party? Because he was a fungi to be with!",
    "Why did the nurse go to the bank? To get her flu shot!",
    "Why did the orange go to the doctor? It wasn't peeling well!",
    "Why did the pancake go to space? To see the syrup!",
    "Why did the penguin go to the doctor? He had a chill!",
    "Why did the piano go to the doctor? It had a flat key!",
    "Why did the pirate learn to talk like a parrot? Because he wanted to be a Polly-glot!",
    "Why did the programmer quit his job? He didn't get arrays!",
    "Why did the rabbit go to the doctor? He had a hopping cough!",
    "Why did the robot go to the bar? For oil and lubrication!",
    "Why did the sandwich go to the doctor? It was bread and ailing!",
    "Why did the skeleton go to the barbecue? He wanted to have a spare rib!",
    "Why did the snake go to the doctor? He had a slithery cough!",
    "Why did the squirrel go to the doctor? It had a nut allergy!",
    "Why did the Superman go to the doctor? He had a krypto-cough!",
    "Why did the turtle go to the doctor? He had shell-itis!",
    "Why did the vampire go to the dentist? He needed a new set of fangs!",
    "Why did the whale go to the doctor? He had a case of the blues!",
    "Why did the witch go to the doctor? She had a spell of dizziness!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the actor fall through the floorboards? They were going through a stage!",
    "Why did a scarecrow win a Nobel prize? He was outstanding in his field!",
    "Why are peppers the best at archery? Because they habanero!",
    "What did the duck say after she bought chapstick? Put it on my bill!",
    "Why did an old man fall in a well? Because he couldn’t see that well!",
    "What do you call a fake noodle? An impasta!",
    "What did the three-legged dog say when he walked into a saloon? “I’m looking for the man who shot my paw!",
    "How do you tell the difference between a bull and a cow? It is either one or the udder!",
    "What’s red and smells like blue paint? Red paint!",
    "What’s the difference between a hippo and a Zippo? One is very heavy, the other is a little lighter!",
    "Why can’t you send a duck to space? Because the bill would be astronomical!",
    "What does Jeff Bezos do before he goes to sleep? He puts his PJ-Amazon!",
    "What happened when the world's tongue-twister champion got arrested? They gave him a tough sentence!",
    "What did the mama cow say to the calf? It’s pasture bedtime!",
    "How does a vampire start a letter? Tomb it may concern!",
    "What do you call an illegally parked frog? Toad!",
    "What did one plate say to the other? Dinner is on me!",
    "Why do hummingbirds hum? Because they don’t know the words!",
    "What do sprinters eat before a race? Nothing. They fast!",
    "Two muffins are baking in an oven. One of them looks to the other and says, Phew, it's getting hot in here! The other looks back and says, Ack! A talking muffin!",
    "What do cats eat for breakfast? Mice Crispies!",
    "What do you call an elephant that doesn’t matter? An irrelephant!",
    "What do you get when you cross a rabbit with shellfish? An oyster bunny!",
    "Where do polar bears keep their money? In a snow bank!",
    "Why did the pony get sent to his room? He wouldn’t stop horsing around!",
    "What kind of dog does a magician have? A Labracadabrador!",
    "Where do cows go on Friday nights? They go to the moo-vies!",
    "Why couldn't the pony sing “Happy Birthday?” Because she was just a little hoarse!",
    "How do you make an octopus laugh? With ten-tickles!",
    "How do you keep a bull from charging? Take away its credit card!",
    "Why can’t a leopard hide? Because he’s always spotted!",
    "What do frogs order at fast-food restaurants? French flies!",
    "What do you get from a pampered cow? Spoiled milk!",
    "What do you call an alligator who solves mysteries? An investigator!",
    "Why is a snake difficult to fool? You can’t pull its leg!",
    "What kind of socks do grizzlies wear? None, they have bear feet!",
    "What do you get when you cross a snail with a porcupine? A slowpoke!",
    "What did the dog say when it sat on sandpaper? Ruff!",
    "What's a cat's favorite dessert? Chocolate mouse!",
    "What fish only swims at night? Starfish!",
    "What does a triceratops sit on? Its tricera-bottom!",
    "What’s a piece of bread’s least favorite chore? Doing a loaf of laundry.",
    "What did the bunny say to the carrot? It’s been nice gnawing you!",
    "What do you call a sad strawberry? A blueberry!",
    "Why did the tomato blush? Because it saw the salad dressing!",
    "What did the pizza say to the topping? I never sau-sage a pretty face!",
    "Which vegetable do sailors hate the most? Leeks!",
    "What do you call a cheese that’s not yours? Nacho cheese!",
    "Why did the cookie go to the nurse? Because he felt crummy!",
    "What kind of room doesn’t have doors? A mushroom!",
    "What kind of key opens a banana? A mon-key!",
    "What happens when a grape gets run over crossing the street? A traffic jam!",
    "What does garlic do when it gets hot? It takes its cloves off!",
    "Where does fruit go on vacation? Pear-is!",
    "Why did the melons choose not to get married? Because they cantaloupe!",
    "What does a lemon say when it answers the phone? Yellow!",
    "What did one dried fruit say when another asked it to the movies? It's a date!",
    "Why do bees have sticky hair? They use honeycombs!",
    "What does a cow call an earthquake? A milkshake!",
    "Why did the man go to the yogurt museum? To get a little culture!",
    "Why couldn't the sesame seed climb up the hill? Because it was on a roll!",
    "Why can't you trust tacos? Because they always spill the beans!",
    "How come no one picks statistics as their favorite subject? It’s just average.",
    "Why did two 4s skip dinner? Because they already 8!",
    "Did you hear about the mathematician who’s afraid of negative numbers? He’ll stop at nothing to avoid them!",
    "What did the triangle feel sorry for the circle? Because it’s pointless!",
    "Why was the math book sad? It had too many problems!",
    "Did you hear about the rancher who had 97 cows in his field?When he rounded them up, he had 100!",
    "Why couldn’t the angle get a loan? Because his parents wouldn’t cosine", !
    "What do you call a number that can’t stay in one place? A roamin’ numeral!",
    "Why should you never trust someone writing on graph paper? Because they must be plotting something!",
    "What do you call two guys who love math? Algebros!",
    "What do you get when you divide a Jack o' lantern by its diameter? Pumpkin pi!",
    "What did the 90° angle say after an argument?",
    "It turns out, I was right!",
    "What tool do mathematicians use most? Multi-pliers!",
    "Why did the student get upset when their teacher called them average? It was a mean thing to say!",
    "If a math teacher had four apples in one hand and five apples in the other hand, what would they have altogether? Really big hands!",
    "What did the 0 say to the 8? Nice belt!",
    "Why was 6 afraid of 7? Because 7, 8, 9!",
    "Why should you never start a conversation with pi? It'll just go on forever!",
    "What is a bird’s favorite type of math? OWL-gebra!",
    "Why do teenagers travel in groups of threes and fives? Because they can’t even!",
    "Why did the robber take a bath before he left the scene of the crime? He wanted to make a clean getaway!",
    "Why does it take pirates a long time to learn the alphabet? Because they can spend years at C!",
    "What did one snowman say to the other snowman? It smells like carrots over here!",
    "What did one wall say to the other wall? I’ll meet you at the corner!",
    "Why did the kid throw his clock out the window? Because he wanted to see time fly!",
    "What do you call a huge pile of cats? A meow-ntain!",
    "Why wouldn’t the shrimp share his treasure? Because he was a little shellfish!",
    "Why is Cinderella bad at soccer? Because she’s always running away from the ball!",
    "What does a rain cloud wear under its clothes? Thunderwear!",
    "Why do vampires seem sick all the time? Because they’re always coffin!",
    "How do you get an astronaut’s baby to stop crying? You rocket!",
    "Why are ghosts bad liars? Because you can see right through them!",
    "Why are spiders so smart? They can find everything on the web!",
    "What are mummies' favorite lunches? Wraps!",
    "How does Darth Vader like his toast? On the dark side!",
    "Why are mountains so funny? They're just hill areas!",
    "Why did the student eat his homework?Because his teacher told him it would be a piece of cake!",
    "What is the Easter bunny’s favorite type of music? Hip-hop!",
    "Why did Beethoven get rid of his chickens? All they ever said was, “Bach, Bach, Bach!”",
    "Why did the man name his dogs Rolex and Timex? Because they were watchdogs!",
    "Why is grass so dangerous? Because it’s full of blades",
    "What did the teacher say when a book fell on their head? I have only my shelf to blame.",
    "What kind of tree can fit in one hand? A palm tree!",
    "How do they keep the basketball arena cool? They fill it with fans!",
    "What does a book do to keep warm in the winter? It puts on a jacket!",
    "What did the lightbulb say to its sweetheart? I wuv you a watt!",
    "What’s the difference between a guitar and a fish?You can tune a guitar, but you can’t tuna fish!",
    "What did the fisherman say to the magician? Pick a cod, any cod!",
    "Why did the picture go to prison? Because it was framed!",
    "Why do bicycles fall over? Because they’re two-tired!",
    "If a seagull flies over the sea, what flies over the bay? A bagel!",
    "What does the ocean do when it sees its friends? It waves!",
    "Why did the golfer wear two pairs of pants? Just in case he got a hole in one!",
    "Why was the broom late? It over-swept!",
    "What did the paper say to the pencil? Write on!",
    "What do you call a belt made of watches? A waist of time!",
    "Where do sailboats go when they're sick? To the dock!",
    "How does the moon cut his hair? Eclipse it!",
    "What do you do when a lemon gets sick? You give it lemon-aid!",
    "What’s worse than raining cats and dogs? Hailing taxis!",
    "How can you tell if a tree is a dogwood tree? By its bark!",
    "What do astronauts do before throwing a party? They planet!",
    "What did the family say when they lost 25% of their roof? Oof.",
    "Why are elevator jokes so good? They work on many levels!",
    "What's worse than finding a worm in your apple? Finding half a worm in your apple!",
    "What do you call a boomerang that doesn't come back? A stick!",
    "What do you call a bear with no ears? A “B!”",
    "What do pirates pay for corn? A buck an ear!",
    "Which hand is it better to write with? Neither, it’s better to write with a pencil!",
    "What do you call a fish with no eye? A fsh!",
    "Why are balloons so expensive? Inflation!",
    "What breed of dog can jump higher than a skyscraper? Any breed of dog. Skyscrapers can’t jump!",
    "Why can't you trust atoms? They make up everything!",
    "What's brown and sticky? A stick!",
    "Why was the calendar afraid? Its days were numbered!",
    "What's E.T. short for? Because he's only got little legs!",
    "Did you hear about the guy who invented the knock-knock joke? He won the no-bell prize!",
    "Why can’t a hand be 12 inches long? Because then it would be a foot!",
    "Why is it hard to understand volunteers? Because they make no cents!",
    "How much does it cost Santa to park his sleigh? Nothing, it's on the house!",
    "How is it that I only know 25 letters of the alphabet? I just don't know y!",
    "When does a regular joke become a dad joke? When it becomes apparent!",
    "What did the cat say when it fell down the stairs? Me-ow!",
    "Where do pencils come from? Pennsylvania!",
    "Why can't you tell a joke to an egg? It might crack up!",
    "Why are fish so smart? Because they live in schools!",
    "What did the big flower say to the little flower? Hi, bud!",
    "How can you make a tissue dance? Put a little boogie in it!",
    "What did the buffalo say when his little boy left for school? Bison!",
    "What animal can you always find at a baseball game? A bat!",
    "Why did the boy throw a stick of butter out the window? Because he wanted to see a butterfly!",
    "What did Baby Corn say to Mama Corn? Where is Pop Corn?",
    "What do you call a train with a cold? A-choo choo train!",
    "Where do elephants pack their clothes? In their trunks!",
    "What do you call a fly without wings? A walk!",
    "What do you call a duck that gets straight-As? A wise quacker!",
    "Why do giraffes have such long necks? Because they have smelly feet!",
    "What did the cop say to their tummy? You're under a vest!",
    "Why did the teddy bear not ask for dessert? Because he was already so stuffed!",
    "Which bird is always out of breath? A puffin!",
    "What's a witch's favorite school subject? Spelling!",
    "How do you talk to a giant? Use big words!",
    "Where do sheep go to get their hair cut? The baa-baa shop!",
    "What do you call a dinosaur that wears glasses? Tyrannosaurus Specs",
    "What do you call a line of rabbits jumping backwards? A receding hare-line!",
    "What has four wheels and flies? A garbage truck!",
    "What did one eye say to the other eye? Between us, something smells!",
    "What did the sink say to the toilet? Wow, you look really flushed!",
    "What gets wetter the more that it dries? A towel!",
    "What did the traffic light say to the car? Look away, I’m about to change!",
    "What can you catch, but never throw? A cold!",
    "What has more letters than the alphabet? The post office!",
    "What's black and white and read all over? A newspaper!",
    "What's black and white and red all over? A sunburned zebra!",
    "What runs around a baseball field but never moves? A fence!",
    "What is brown and hairy and wears sunglasses? A coconut on vacation!",
    "What time is it when an elephant sits on your fence? Time to get a new fence!",
    "What's the difference between boogers and broccoli? Kids don't eat broccoli!",
    "What did the apple say to the worm? Nothing, apples can't talk!",
    "What musical instrument can you find in the bathroom? A tuba toothpaste!",
    "What do you call a dinosaur with bad vision? A Do-you-think-he-sarus!",
    "What do you get when you cross a centipede with a parrot? A walkie talkie!",
    "Which dinosaur has the best vocabulary? The thesaurus!",
    "What do you call two bananas? A pair of slippers!"
]
let randomIn = Math.floor(Math.random() * 264);
let randomJoke = jokes[randomIn];
let a = document.getElementById("random-joke");
a.innerHTML = (`" ${randomJoke} "`);